apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-app
  description: An example of a go application.
  annotations:
    github.com/project-slug: Hozalex/sample-app
    backstage.io/kubernetes-id: sample-app
spec:
  type: service
  owner: hozalex
  lifecycle: experimental
