apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-app
  description: An example of a go application.
  annotations:
    github.com/project-slug: Hozalex/sample-app
    backstage.io/kubernetes-id: sample-app
    backstage.io/kubernetes-namespace: default
    backstage.io/techdocs-ref: dir:.
  tags:
    - go
spec:
  type: service
  owner: developers
  lifecycle: development
  system: platform
  