apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    backstage.io/kubernetes-id: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        backstage.io/kubernetes-id: sample-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: sample-app
        image: ghcr.io/hozalex/sample-app:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
